name: "Check if Tag Exists"
description: "Checks if a GitHub tag exists using the GitHub API."

inputs:
  tag:
    description: "The tag name to check (e.g., v1.2.3)"
    required: true
  github-token:
    description: "GitHub token for API access"
    required: true

outputs:
  exists:
    description: "true if the tag exists, false otherwise"
    value: ${{ steps.check-tag.outputs.exists }}
  tag-sha:
    description: "SHA of the tag if it exists, empty otherwise"
    value: ${{ steps.check-tag.outputs.tag-sha }}

runs:
  using: "composite"
  steps:
    - name: Check if tag exists via GitHub API
      id: check-tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TAG: ${{ inputs.tag }}
      run: |
        set -e
        OWNER_REPO=$(echo "$GITHUB_REPOSITORY")
        TAG_NAME="$TAG"
        API_URL="https://api.github.com/repos/$OWNER_REPO/git/refs/tags/$TAG_NAME"
        RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$API_URL")
        TAG_SHA=$(echo "$RESPONSE" | jq -r '.object.sha // empty')
        if [[ -n "$TAG_SHA" && "$TAG_SHA" != "null" ]]; then
          echo "Tag $TAG_NAME exists: $TAG_SHA"
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "tag-sha=$TAG_SHA" >> $GITHUB_OUTPUT
        else
          echo "Tag $TAG_NAME does not exist"
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "tag-sha=" >> $GITHUB_OUTPUT
        fi
