name: "Setup Node.js"
description: "Setup Node.js with specified version"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "lts/*"
  
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
