name: "Verify Git Tag Signature"
description: "Checks if a git tag is GPG signed/verified via the GitHub API."

inputs:
  tag-sha:
    description: "The SHA of the tag to verify."
    required: true
  github-token:
    description: "GitHub token for API access."
    required: true

outputs:
  verified:
    description: "Whether the tag is GPG verified."
    value: ${{ steps.verify.outputs.verified }}
  reason:
    description: "Reason for the verification result."
    value: ${{ steps.verify.outputs.reason }}

runs:
  using: "composite"
  steps:
    - name: Verify tag signature
      id: verify
      shell: bash
      run: |
        TAG_SHA="${{ inputs.tag-sha }}"
        TAG_VERIFY_RESPONSE=$(curl -s -H "Authorization: token ${{ inputs.github-token }}" \
          "https://api.github.com/repos/${{ github.repository }}/git/tags/$TAG_SHA")
        VERIFIED=$(echo "$TAG_VERIFY_RESPONSE" | jq -r '.verification.verified // false')
        REASON=$(echo "$TAG_VERIFY_RESPONSE" | jq -r '.verification.reason // "unknown"')
        echo "verified=$VERIFIED" >> $GITHUB_OUTPUT
        echo "reason=$REASON" >> $GITHUB_OUTPUT
        echo "🔐 Tag verified: $VERIFIED (reason: $REASON)"
