name: "Publish to NPM"
description: "Composite action for publishing to NPM registry"

inputs:
  package-name:
    description: "Name of the package to publish"
    required: true
  version:
    description: "Version to publish"
    required: true
  node-version:
    description: "Node.js version to use"
    required: false
    default: "lts/*"
  package-manager:
    description: "Package manager (npm or yarn)"
    required: false
    default: "npm"
  publish-command:
    description: "Command to publish the package"
    required: true
  dry-run:
    description: "Dry run mode - validate everything but don't publish"
    required: false
    default: "false"
  npm-token:
    description: "NPM token for authentication"
    required: true
  artifact-name:
    description: "Name of the build artifact to download"
    required: false
    default: "build-artifacts"

outputs:
  published:
    description: "Whether the package was successfully published"
    value: ${{ steps.publish-package.outputs.published }}

runs:
  using: composite
  steps:
    - name: Update Summary - NPM Publishing Start
      shell: bash
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          echo "## 🧪 Dry Run - NPM Publishing Validation" >> $GITHUB_STEP_SUMMARY
          echo "- 🔍 Validating NPM publication for ${{ inputs.package-name }}@${{ inputs.version }} (NO PUBLISHING WILL OCCUR)" >> $GITHUB_STEP_SUMMARY
        else
          echo "## 📦 NPM Publishing Progress" >> $GITHUB_STEP_SUMMARY
          echo "- 🔄 Starting NPM publication for ${{ inputs.package-name }}@${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Generate publish command
      id: generate-command
      shell: bash
      run: |
        # Generate appropriate publish command based on repository visibility and inputs
        PACKAGE_NAME="${{ inputs.package-name }}"
        CUSTOM_CMD="${{ inputs.publish-command }}"

        if [ -n "$CUSTOM_CMD" ]; then
          echo "🔧 Using custom publish command"
          FINAL_CMD="$CUSTOM_CMD"
        else
          echo "🔧 Generating publish command based on repository and package settings"
          
          # Check if repository is public or private
          REPO_VISIBILITY="${{ github.event.repository.private == false && 'public' || 'private' }}"
          echo "📊 Repository visibility: $REPO_VISIBILITY"
          
          # Determine access level (default based on repo visibility, can be overridden)
          if [ "$REPO_VISIBILITY" = "public" ]; then
            ACCESS_LEVEL="public"
          else
            ACCESS_LEVEL="restricted"
          fi
          
          echo "🔒 Package access level: $ACCESS_LEVEL"
          
          # Generate command
          if [ "${{ inputs.package-manager }}" = "yarn" ]; then
            if [ "$ACCESS_LEVEL" = "public" ]; then
              FINAL_CMD="yarn publish --access public"
            else
              FINAL_CMD="yarn publish --access restricted"
            fi
          else
            if [ "$ACCESS_LEVEL" = "public" ]; then
              FINAL_CMD="npm publish --access public"
            else
              FINAL_CMD="npm publish --access restricted"
            fi
          fi
        fi

        echo "📝 Final publish command: $FINAL_CMD"
        echo "command=$FINAL_CMD" >> $GITHUB_OUTPUT

    - name: Publish package to NPM
      id: publish-package
      uses: CLDMV/.github/.github/actions/npm/steps/publish-package@v1
      with:
        registry-name: "NPM"
        registry-url: "https://registry.npmjs.org"
        package-name: ${{ inputs.package-name }}
        version: ${{ inputs.version }}
        node-version: ${{ inputs.node-version }}
        package-manager: ${{ inputs.package-manager }}
        publish-command: ${{ steps.generate-command.outputs.command }}
        dry-run: ${{ inputs.dry-run }}
        auth-token: ${{ inputs.npm-token }}
        artifact-name: ${{ inputs.artifact-name }}

    - name: Update Summary - NPM Success
      if: steps.publish-package.outputs.published == 'true' && inputs.dry-run != 'true'
      shell: bash
      run: |
        # Extract package name for URL (remove @scope/ if present)
        PACKAGE_URL_NAME=$(echo "${{ inputs.package-name }}" | sed 's|^@[^/]*/||')

        # Format version - ensure no double "v" prefix
        VERSION="${{ inputs.version }}"
        if [[ "$VERSION" =~ ^v ]]; then
          DISPLAY_VERSION="$VERSION"
        else
          DISPLAY_VERSION="v$VERSION"
        fi

        echo "- ✅ NPM Registry: Published [${{ inputs.package-name }} $DISPLAY_VERSION](https://www.npmjs.com/package/${{ inputs.package-name }})" >> $GITHUB_STEP_SUMMARY

    - name: Update Summary - Dry Run Success
      if: steps.publish-package.outputs.published == 'true' && inputs.dry-run == 'true'
      shell: bash
      run: |
        echo "- 🧪 **DRY RUN**: NPM Registry validation successful" >> $GITHUB_STEP_SUMMARY
        echo "  - ✅ Package name and version are valid" >> $GITHUB_STEP_SUMMARY
        echo "  - ✅ Authentication token is valid" >> $GITHUB_STEP_SUMMARY
        echo "  - ✅ Publish command generated successfully" >> $GITHUB_STEP_SUMMARY
        echo "  - ✅ All prerequisites met for NPM publication" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "💡 **Would publish**: \`${{ steps.generate-command.outputs.command }}\`" >> $GITHUB_STEP_SUMMARY

    - name: Update Summary - NPM Failure
      if: steps.publish-package.outputs.published != 'true' && inputs.dry-run != 'true'
      shell: bash
      run: |
        echo "- ❌ NPM Registry: Publication failed for ${{ inputs.package-name }}@${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
