name: "Test Tag Creation Methods"
description: "Test tag creation using both Git commands and GitHub API with comprehensive permission validation"

inputs:
  test_tag_name:
    description: "Name of the test tag to create"
    required: true
  target_commit:
    description: "Commit SHA to tag (defaults to HEAD)"
    required: false
    default: ""
  cleanup_tag:
    description: "Whether to clean up the test tag after testing"
    required: false
    default: "true"
  cleanup_all_test_artifacts:
    description: "Whether to clean up ALL test artifacts (releases and tags) matching test-debug pattern"
    required: false
    default: "false"
  use_github_token:
    description: "Whether to use GITHUB_TOKEN instead of app token"
    required: false
    default: "false"
  token:
    description: "Authentication token (app token or GITHUB_TOKEN)"
    required: true
  tagger_name:
    description: "Name for git tagger"
    required: false
    default: "Test Bot"
  tagger_email:
    description: "Email for git tagger"
    required: false
    default: "test-bot@example.com"
  gpg_private_key:
    description: "GPG private key for signing (optional)"
    required: false
    default: ""
  gpg_passphrase:
    description: "GPG passphrase for signing (optional)"
    required: false
    default: ""

outputs:
  overall_result:
    description: "Overall test result (success/failure)"
  git_result:
    description: "Git-based tag creation result"
  api_result:
    description: "API-based tag creation result"
  gpg_result:
    description: "Combined GPG signature verification result (for backward compatibility)"
  api_gpg_result:
    description: "API-based GPG signature verification result"
  git_gpg_result:
    description: "Git-based GPG signature verification result"
  details:
    description: "Detailed test results and error messages"
  api_success:
    description: "Whether API tag creation succeeded"
  git_success:
    description: "Whether Git tag creation succeeded"
  api_release_success:
    description: "Whether API release creation succeeded"
  git_release_success:
    description: "Whether Git release creation succeeded"
  token_type:
    description: "Type of token used (app/github)"
  api_tag_verified:
    description: "Whether API-created tag was verified"
  git_tag_verified:
    description: "Whether Git-created tag was verified"

runs:
  using: "node20"
  main: "action.mjs"
