name: "🔐 Fix Unsigned Tags"
description: "Converts unsigned/lightweight tags to properly signed annotated tags"

inputs:
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  gpg_enabled:
    description: "Whether GPG signing should be used (auto-detected from workflow)"
    required: false
    default: "false"
  dry_run:
    description: "Show what would be done without making changes"
    required: false
    default: "false"
  tags_detailed:
    description: "JSON array of detailed tag objects from previous step"
    required: true
  tagger_name:
    description: "Bot tagger name for new tags"
    required: false
  tagger_email:
    description: "Bot tagger email for new tags"
    required: false
  gpg_private_key:
    description: "GPG private key for signing"
    required: false
  gpg_passphrase:
    description: "GPG passphrase"
    required: false

outputs:
  updated_tags_detailed:
    description: "Updated JSON array of detailed tag objects after processing"
    value: ${{ steps.fix-tags.outputs.updated-tags-detailed }}
  fixed_count:
    description: "Number of tags that were fixed"
    value: ${{ steps.fix-tags.outputs.fixed-count }}
  fixed_tags:
    description: "JSON array of tag names that were fixed"
    value: ${{ steps.fix-tags.outputs.fixed-tags }}
  summary_json:
    description: "Complete summary JSON with title, description, and detailed results"
    value: ${{ steps.fix-tags.outputs.summary-json }}

runs:
  using: "composite"
  steps:
    - name: Fix unsigned tags
      id: fix-tags
      shell: bash
      run: node ${{ github.action_path }}/action.mjs
      env:
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_TAGS_DETAILED: ${{ inputs.tags_detailed }}
        INPUT_GPG_ENABLED: ${{ inputs.gpg_enabled }}
        INPUT_TAGGER_NAME: ${{ inputs.tagger_name }}
        INPUT_TAGGER_EMAIL: ${{ inputs.tagger_email }}
        INPUT_GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        INPUT_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
