# Individual repo: .github/workflows/ci.yml
name: 🧪 CI Tests & Build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  ci:
    uses: CLDMV/.github/.github/workflows/ci.yml@v1
    with:
      package_name: "@cldmv/slothlet" # Required: Your NPM package name
      # Optional parameters:
      # node_version: "lts/*" # Use if you want a single version
      min_node_version: "16.4" # Minimum Node.js version for matrix
      # max_node_major: "22" # (Optional) Maximum Node.js major version
      package_manager: "npm"
      test_command: "npm test"
      build_command: "npm run build:ci"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # skip_performance_tests: false
      # skip_matrix_tests: false
