# Individual repo: .github/workflows/ci.yml
name: 🧪 CI Tests & Build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  ci:
    uses: CLDMV/.github/workflows/ci.yml@v1
    with:
      package_name: "@cldmv/slothlet" # Required
      node_version: "lts/*"
      test_command: "npm test"
      lint_command: "npm run lint"
      build_command: "npm run build:ci"
      entry_test_command: "npm run test:entry"
      performance_test_command: "npm run test:performance"
      test_matrix_versions: '["18", "20", "21"]'
      # Optional: skip certain tests
      # skip_lint: false
      # skip_entry_tests: false
      # skip_performance_tests: false
      # skip_matrix_tests: false
