# Individual repo: .github/workflows/release.yml
name: 🚀 Release PR Creation

on:
  push:
    branches-ignore: [master, main]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  create-release-pr:
    uses: CLDMV/.github/.github/workflows/release.yml@v1
    with:
      package_name: "@cldmv/slothlet" # Required: Your NPM package name
      # Optional parameters:
      # node_version: "lts/*" # Use if you want a single version
      min_node_version: "16.4" # Minimum Node.js version for matrix
      # max_node_major: "22" # (Optional) Maximum Node.js major version
      package_manager: "npm"
      build_command: "npm run build:ci"
      version_bump: "patch" # or "minor", "major"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
