name: 🧪 Test Tag Creation Debug

on:
  workflow_dispatch:
    inputs:
      test_tag_name:
        description: "Tag name to create for testing (e.g., test-debug-v1.0.0)"
        required: true
        default: "test-debug-v1.0.0"
      target_commit:
        description: "Commit SHA to tag (leave empty for HEAD)"
        required: false
        default: ""
      cleanup_tag:
        description: "Clean up test tags after testing"
        required: false
        type: boolean
        default: true
      set_permissions:
        description: "Test with explicit workflow permissions set"
        required: false
        type: boolean
        default: false
      test_app_permissions:
        description: "Test app token permission scenarios"
        required: false
        type: boolean
        default: true

jobs:
  test-without-permissions:
    name: "🧪 Test Without Permissions"
    uses: CLDMV/.github/.github/workflows/test-tag-creation.yml@master
    with:
      package_name: "@cldmv/test-package" # Replace with your actual package name
      test_tag_name: ${{ inputs.test_tag_name }}
      target_commit: ${{ inputs.target_commit }}
      cleanup_tag: ${{ inputs.cleanup_tag }}
      set_permissions: false
      test_app_permissions: false
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      TAGGER_NAME: ${{ secrets.TAGGER_NAME }}
      TAGGER_EMAIL: ${{ secrets.TAGGER_EMAIL }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  test-with-workflow-permissions:
    name: "🧪 Test With Workflow Permissions"
    if: inputs.set_permissions == true
    uses: CLDMV/.github/.github/workflows/test-tag-creation.yml@master
    with:
      package_name: "@cldmv/test-package" # Replace with your actual package name
      test_tag_name: ${{ inputs.test_tag_name }}
      target_commit: ${{ inputs.target_commit }}
      cleanup_tag: ${{ inputs.cleanup_tag }}
      set_permissions: true
      test_app_permissions: false
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      TAGGER_NAME: ${{ secrets.TAGGER_NAME }}
      TAGGER_EMAIL: ${{ secrets.TAGGER_EMAIL }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  test-with-app-permissions:
    name: "🧪 Test With App Token Permissions"
    if: inputs.test_app_permissions == true
    uses: CLDMV/.github/.github/workflows/test-tag-creation.yml@master
    with:
      package_name: "@cldmv/test-package" # Replace with your actual package name
      test_tag_name: ${{ inputs.test_tag_name }}
      target_commit: ${{ inputs.target_commit }}
      cleanup_tag: ${{ inputs.cleanup_tag }}
      set_permissions: false
      test_app_permissions: true
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      TAGGER_NAME: ${{ secrets.TAGGER_NAME }}
      TAGGER_EMAIL: ${{ secrets.TAGGER_EMAIL }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  test-with-permissions:
    name: "🧪 Test With Full Permissions"
    if: inputs.set_permissions == true && inputs.test_app_permissions == true
    uses: CLDMV/.github/.github/workflows/test-tag-creation.yml@master
    with:
      package_name: "@cldmv/test-package" # Replace with your actual package name
      test_tag_name: ${{ inputs.test_tag_name }}
      target_commit: ${{ inputs.target_commit }}
      cleanup_tag: ${{ inputs.cleanup_tag }}
      set_permissions: true
      test_app_permissions: true
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      TAGGER_NAME: ${{ secrets.TAGGER_NAME }}
      TAGGER_EMAIL: ${{ secrets.TAGGER_EMAIL }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
