name: "Download Artifacts"
description: "Reusable step to download build artifacts by name."

inputs:
  artifact-name:
    description: "Name of the artifact to download (e.g., build-artifacts-lts)"
    required: true
  path:
    description: "Destination path for the downloaded artifact(s)"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}
