name: "Generate Release Notes"
description: "Generate comprehensive release notes from git history"

inputs:
  version:
    description: "Version number for the release"
    required: true
  package-name:
    description: "Name of the package being released"
    required: true
  package-manager:
    description: "Package manager used (npm or yarn)"
    required: false
    default: "npm"

outputs:
  release-notes:
    description: "Generated release notes in markdown format"
    value: ${{ steps.generate.outputs.release-notes }}

runs:
  using: "composite"
  steps:
    - name: Get commit range for release notes
      id: commit-range
      uses: CLDMV/.github/.github/actions/git/steps/get-commit-range@v1
      with:
        debug: "false"

    - name: Generate release notes
      id: generate
      shell: bash
      run: |
        # Set environment variables for the Node.js script
        export VERSION="${{ inputs.version }}"
        export COMMITS='${{ steps.commit-range.outputs.commits }}'
        export HAS_COMMITS="${{ steps.commit-range.outputs.has-commits }}"
        export PACKAGE_NAME="${{ inputs.package-name }}"
        export PACKAGE_MANAGER="${{ inputs.package-manager }}"

        # Run the Node.js script
        node "${{ github.action_path }}/action.mjs"
