name: "Publish to GitHub Packages"
description: "Composite action for publishing to GitHub Packages registry"

inputs:
  package-name:
    description: "Name of the package to publish"
    required: true
  version:
    description: "Version to publish"
    required: true
  node-version:
    description: "Node.js version to use"
    required: false
    default: "lts/*"
  package-manager:
    description: "Package manager (npm or yarn)"
    required: false
    default: "npm"
  publish-command:
    description: "Command to publish the package"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  artifact-name:
    description: "Name of the build artifact to download"
    required: false
    default: "build-artifacts"

outputs:
  published:
    description: "Whether the package was successfully published"
    value: ${{ steps.publish-package.outputs.published }}

runs:
  using: composite
  steps:
    - name: Update Summary - GitHub Packages Start
      shell: bash
      run: |
        echo "## 📦 GitHub Packages Publishing Progress" >> $GITHUB_STEP_SUMMARY
        echo "- 🔄 Starting GitHub Packages publication for ${{ inputs.package-name }}@${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Publish package to GitHub Packages
      id: publish-package
      uses: CLDMV/.github/.github/actions/npm/steps/publish-package@v1
      with:
        registry-name: "GitHub Packages"
        registry-url: "https://npm.pkg.github.com"
        package-name: ${{ inputs.package-name }}
        version: ${{ inputs.version }}
        node-version: ${{ inputs.node-version }}
        package-manager: ${{ inputs.package-manager }}
        publish-command: ${{ inputs.publish-command }}
        auth-token: ${{ inputs.github-token }}
        artifact-name: ${{ inputs.artifact-name }}

    - name: Update Summary - GitHub Packages Success
      if: steps.publish-package.outputs.published == 'true'
      shell: bash
      run: |
        # Extract org and package name for GitHub Packages URL
        ORG_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        PACKAGE_NAME=$(echo "${{ inputs.package-name }}" | sed 's|^@[^/]*/||')
        echo "- ✅ GitHub Packages: Published [${{ inputs.package-name }}@${{ inputs.version }}](https://github.com/$ORG_NAME/$PACKAGE_NAME/pkgs/npm/$PACKAGE_NAME) successfully" >> $GITHUB_STEP_SUMMARY

    - name: Update Summary - GitHub Packages Failure
      if: steps.publish-package.outputs.published != 'true'
      shell: bash
      run: |
        echo "- ❌ GitHub Packages: Publication failed for ${{ inputs.package-name }}@${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
