name: "Create GitHub Release via API"
description: "Reusable action to create a GitHub release, supporting prerelease, draft, and asset uploads."

inputs:
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  tag_name:
    description: "Tag name for the release (e.g. v1.2.3)"
    required: true
  name:
    description: "Release name (title)"
    required: true
  body:
    description: "Release notes content in markdown"
    required: false
    default: ""
  is_prerelease:
    description: "Whether this is a prerelease"
    required: false
    default: "false"
  is_draft:
    description: "Whether this is a draft release"
    required: false
    default: "false"
  assets:
    description: "Comma-separated list of file paths to upload as release assets"
    required: false
    default: ""
  repo:
    description: "owner/repo (defaults to current repository)"
    required: false

outputs:
  release_id:
    description: "ID of the created GitHub release"
  html_url:
    description: "URL of the created release"
  upload_url:
    description: "Upload URL for assets"

runs:
  using: "node20"
  main: "action.mjs"
