name: "Detect Repository Config"
description: "Complete reusable workflow for detecting repository configuration"

on:
  workflow_call:
    inputs:
      package-manager:
        description: "Package manager (npm or yarn)"
        required: false
        type: string
        default: "npm"
      custom-npm-command:
        description: "Custom NPM publish command"
        required: false
        type: string
        default: ""
      custom-github-packages-command:
        description: "Custom GitHub Packages publish command"
        required: false
        type: string
        default: ""
    secrets:
      GITHUB_TOKEN:
        required: true
    outputs:
      npm-command:
        description: "NPM publish command"
        value: ${{ jobs.detect-repo-config.outputs.npm-command }}
      github-packages-command:
        description: "GitHub Packages publish command"
        value: ${{ jobs.detect-repo-config.outputs.github-packages-command }}
      repo-is-private:
        description: "Whether repository is private"
        value: ${{ jobs.detect-repo-config.outputs.repo-is-private }}

jobs:
  detect-repo-config:
    name: "🔧 Detect Repository Config"
    runs-on: ubuntu-latest
    outputs:
      npm-command: ${{ steps.detect.outputs.npm-command }}
      github-packages-command: ${{ steps.detect.outputs.github-packages-command }}
      repo-is-private: ${{ steps.detect.outputs.repo-is-private }}

    steps:
      - name: Detect repository configuration
        id: detect
        uses: ../utilities/repo-detection.yml
        with:
          package-manager: ${{ inputs.package-manager }}
          custom-npm-command: ${{ inputs.custom-npm-command }}
          custom-github-packages-command: ${{ inputs.custom-github-packages-command }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
