name: "Generate Comprehensive Changelog"
description: "Generate detailed changelog with breaking changes, features, fixes, and contributors"

inputs:
  commits:
    description: "JSON array of categorized commits from get-commit-range"
    required: false
  commits-file:
    description: "Path to JSON file containing commits array (preferred over commits to avoid env-var size limits)"
    required: false
  commit-range:
    description: "Git commit range (fallback if commits not provided)"
    required: false
  use-single-commit-message:
    description: "Whether to use commit message directly for single commits (true for publish, false for PR)"
    required: false
    default: "false"

outputs:
  changelog-content:
    description: "Generated changelog content in markdown format"
    value: ${{ steps.changelog.outputs.changelog-content }}

runs:
  using: "composite"
  steps:
    - name: Generate comprehensive changelog
      id: changelog
      shell: bash
      env:
        # Pass the file path rather than the full JSON to avoid "Argument list too long" errors
        COMMITS_FILE: ${{ inputs.commits-file }}
        COMMITS_INPUT: ${{ inputs.commits }}
        COMMIT_RANGE_INPUT: ${{ inputs.commit-range }}
        USE_SINGLE_COMMIT_MESSAGE: ${{ inputs.use-single-commit-message }}
      run: |
        node "${{ github.action_path }}/action.mjs"
