name: "Create Pull Request"
description: "Create or update a pull request with release changes"

inputs:
  title:
    description: "PR title"
    required: true
  base-branch:
    description: "Base branch for the PR"
    required: true
  head-branch:
    description: "Head branch for the PR"
    required: true
  body-content:
    description: "PR body content"
    required: true
  labels:
    description: "Comma-separated list of labels"
    required: false
    default: "release"

outputs:
  pr-number:
    description: "Number of the created/existing PR"
    value: ${{ steps.create-pr.outputs.pr-number }}
  pr-created:
    description: "Whether a new PR was created (false if existing PR was found)"
    value: ${{ steps.create-pr.outputs.pr-created }}

runs:
  using: "composite"
  steps:
    - name: Create PR body file
      shell: bash
      run: |
        cat > PR_BODY.md << 'EOF'
        ${{ inputs.body-content }}
        EOF

    - name: Create or update pull request
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Check if PR already exists
        EXISTING_PR=$(gh pr list --head ${{ inputs.head-branch }} --base ${{ inputs.base-branch }} --json number --jq '.[0].number' 2>/dev/null || echo "")

        if [ -n "$EXISTING_PR" ]; then
          echo "PR already exists: #$EXISTING_PR"
          echo "pr-number=$EXISTING_PR" >> $GITHUB_OUTPUT
          echo "pr-created=false" >> $GITHUB_OUTPUT
        else
          # Create new PR
          PR_URL=$(gh pr create \
            --title "${{ inputs.title }}" \
            --base ${{ inputs.base-branch }} \
            --head ${{ inputs.head-branch }} \
            --body-file PR_BODY.md \
            --label "${{ inputs.labels }}")
          
          # Extract PR number from URL
          PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]\+$')
          
          echo "Created PR: #$PR_NUMBER"
          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr-created=true" >> $GITHUB_OUTPUT
        fi
