name: "Install Dependencies"
description: "Install dependencies using the appropriate package manager"

inputs:
  package-manager:
    description: "Package manager to use (npm or yarn)"
    required: false
    default: "npm"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "yarn" ]; then
          yarn install --frozen-lockfile
        else
          npm ci
        fi




