name: "Build and Test NPM Package"
description: "Complete reusable workflow for building and testing NPM packages"

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "lts/*"
      package-manager:
        description: "Package manager (npm or yarn)"
        required: false
        type: string
        default: "npm"
      test-command:
        description: "Command to run pre-build tests"
        required: false
        type: string
        default: "npm test"
      build-command:
        description: "Command to build package"
        required: false
        type: string
        default: "npm run build:ci"

jobs:
  build-and-test:
    name: "🏗️ Build & Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ../../common/steps/checkout-code.yml

      - name: Setup Node.js
        uses: ../../common/steps/setup-node.yml
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        uses: ../steps/install-dependencies.yml
        with:
          package-manager: ${{ inputs.package-manager }}

      - name: Run pre-build tests
        uses: ../../common/steps/run-tests.yml
        with:
          test-command: ${{ inputs.test-command }}
          environment: development

      - name: Build package
        uses: ../../common/steps/build-project.yml
        with:
          build-command: ${{ inputs.build-command }}
          environment: production

      - name: Upload build artifacts
        uses: ../../common/steps/upload-artifacts.yml
        with:
          artifact-name: build-artifacts
          artifact-path: |
            dist/
            lib/
            build/
            *.tgz
            package.json
            package-lock.json
            yarn.lock
          retention-days: 1
