name: "🔄 Git Tag Operations"
description: "Composite action for updating major version tags"

inputs:
  create-documentation:
    description: "Whether to create/update VERSION_TAGS.md documentation"
    required: false
    default: "true"

outputs:
  major-version:
    description: "The major version tag that was updated"
    value: ${{ steps.update-tags.outputs.major-version }}
  minor-version:
    description: "The minor version tag that was updated"
    value: ${{ steps.update-tags.outputs.minor-version }}
  updated:
    description: "Whether tags were successfully updated"
    value: ${{ steps.update-tags.outputs.updated }}
  has-version-tags:
    description: "Whether version tags were found"
    value: ${{ steps.check-tags.outputs.has_version_tags }}
  should-run:
    description: "Whether the tag update should run"
    value: ${{ steps.should-run.outputs.result }}
  fixed-orphans:
    description: "List of orphaned tags that were fixed"
    value: ${{ steps.fix-orphans.outputs.fixed-tags }}
  orphans-found:
    description: "Whether any orphaned tags were found and fixed"
    value: ${{ steps.fix-orphans.outputs.orphans-found }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: CLDMV/.github/.github/actions/common/steps/checkout-code@v1
      with:
        fetch-depth: 0

    - name: Check for version tags
      id: check-tags
      uses: CLDMV/.github/.github/actions/git/steps/check-version-tags@v1

    - name: Fix orphaned major version tags
      id: fix-orphans
      uses: CLDMV/.github/.github/actions/git/jobs/fix-orphaned-version-tags@v1

    - name: Determine if should run
      id: should-run
      shell: bash
      run: |
        # Run if this is a workflow_call OR if version tags were found on push
        if [ "${{ github.event_name }}" = "workflow_call" ] || [ "${{ steps.check-tags.outputs.has_version_tags }}" = "true" ]; then
          echo "result=true" >> $GITHUB_OUTPUT
          echo "✅ Should run tag updates"
        else
          echo "result=false" >> $GITHUB_OUTPUT
          echo "❌ Skipping tag updates - no version tags found"
        fi

    - name: Get tag name
      id: get-tag
      if: steps.should-run.outputs.result == 'true'
      shell: bash
      run: |
        # Get the tag that triggered this workflow
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          TAG_NAME="${{ github.ref_name }}"
        fi
        echo "tag-name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Processing tag: $TAG_NAME"

    - name: Update major version tags
      id: update-tags
      if: steps.should-run.outputs.result == 'true'
      uses: CLDMV/.github/.github/actions/git/steps/update-major-version-tags@v1
      with:
        tag-name: ${{ steps.get-tag.outputs.tag-name }}

    - name: Generate version documentation
      if: inputs.create-documentation == 'true' && steps.update-tags.outputs.updated == 'true'
      uses: CLDMV/.github/.github/actions/git/steps/generate-version-documentation@v1
      with:
        create-documentation: ${{ inputs.create-documentation }}

    - name: Create summary
      shell: bash
      run: |
        echo "## 🏷️ Version Tag Operations" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Show orphan fixes if any
        if [ "${{ steps.fix-orphans.outputs.orphans-found }}" = "true" ]; then
          echo "### 🔧 Fixed Orphaned Tags" >> $GITHUB_STEP_SUMMARY
          echo "The following major version tags were corrected:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ steps.fix-orphans.outputs.fixed-tags }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        # Show regular tag updates if any
        if [ "${{ steps.update-tags.outputs.updated }}" = "true" ]; then
          echo "### 📌 Version Tags Updated" >> $GITHUB_STEP_SUMMARY
          echo "The following major/minor version tags have been updated:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ steps.update-tags.outputs.major-version }}\` → \`${{ steps.get-tag.outputs.tag-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ steps.update-tags.outputs.minor-version }}\` → \`${{ steps.get-tag.outputs.tag-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        # Show status if no operations
        if [ "${{ steps.fix-orphans.outputs.orphans-found }}" = "false" ] && [ "${{ steps.update-tags.outputs.updated }}" != "true" ]; then
          echo "✅ All version tags are up to date - no changes needed" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Workflows can reference major version tags (e.g., \`@v1\`) for automatic updates." >> $GITHUB_STEP_SUMMARY
