name: "Check Release Commit"
description: "Check if the latest commit is a release commit and determine version bump type"

outputs:
  should-create-pr:
    description: "Whether a release PR should be created"
    value: ${{ steps.check.outputs.should-create-pr }}
  version-bump:
    description: "Type of version bump (major, minor, patch)"
    value: ${{ steps.check.outputs.version-bump }}
  commit-message:
    description: "The commit message that triggered the release"
    value: ${{ steps.check.outputs.commit-message }}
  has-breaking:
    description: "Whether this release has breaking changes"
    value: ${{ steps.check.outputs.has-breaking }}

runs:
  using: "composite"
  steps:
    - name: Check for release commit
      id: check
      shell: bash
      run: |
        # Get the latest commit message and body
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        COMMIT_BODY=$(git log -1 --pretty=format:"%b")

        echo "Latest commit: $COMMIT_MSG"
        echo "commit-message=$COMMIT_MSG" >> $GITHUB_OUTPUT

        # Only trigger on explicit release commits
        if [[ $COMMIT_MSG =~ ^release!: ]]; then
          echo "should-create-pr=true" >> $GITHUB_OUTPUT
          echo "version-bump=major" >> $GITHUB_OUTPUT
          echo "has-breaking=true" >> $GITHUB_OUTPUT
          echo "🚀 Breaking release commit detected - will create major version PR"
        elif [[ $COMMIT_MSG =~ ^release: ]]; then
          echo "should-create-pr=true" >> $GITHUB_OUTPUT
          echo "has-breaking=false" >> $GITHUB_OUTPUT
          
          # Fetch all tags to ensure we have the complete tag history
          echo "🔍 Fetching all tags from remote..."
          git fetch --tags --force
          git fetch origin master --tags
          git fetch origin main --tags 2>/dev/null || true
          
          # Debug: Show available tags
          echo "Available tags after fetch:"
          git tag -l | sort -V | tail -5
          git fetch origin --tags --force 2>/dev/null || true
          
          echo "📋 Available tags after fetch:"
          git tag -l | sort -V | tail -10
          
          # Analyze commits since last release to determine version bump
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tags found, defaulting to minor release"
            echo "version-bump=minor" >> $GITHUB_OUTPUT
          else
            echo "Last tag: $LAST_TAG"
            
            # Debug: Show what commits we're analyzing
            COMMIT_RANGE="$LAST_TAG..HEAD"
            echo "🔍 Analyzing commit range: $COMMIT_RANGE"
            echo "📋 Commits in range:"
            git log $COMMIT_RANGE --oneline | head -10
            
            # Check for breaking changes in the range (exclude previous release commits)
            echo "🔍 Checking for breaking changes..."
            BREAKING_COMMITS=$(git log $COMMIT_RANGE --grep="!" --not --grep="^release" --oneline)
            BREAKING_BODY=$(git log $COMMIT_RANGE --grep="BREAKING CHANGE" --not --grep="^release" --oneline)
            
            if [[ -n "$BREAKING_COMMITS" ]]; then
              echo "⚠️ Breaking commits found:"
              echo "$BREAKING_COMMITS"
            fi
            if [[ -n "$BREAKING_BODY" ]]; then
              echo "⚠️ Breaking change bodies found:"
              echo "$BREAKING_BODY"
            fi
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tags found, defaulting to minor release"
            echo "version-bump=minor" >> $GITHUB_OUTPUT
          else
            echo "Last tag: $LAST_TAG"
            COMMIT_RANGE="$LAST_TAG..HEAD"
            
            echo "🔍 DEBUG: Analyzing commit range: $COMMIT_RANGE"
            echo "🔍 DEBUG: All commits in range:"
            git log $COMMIT_RANGE --oneline || true
            
            # Check for breaking changes in the range (exclude previous release commits)
            BREAKING_COMMITS=$(git log $COMMIT_RANGE --grep="!" --not --grep="^release" --oneline)
            BREAKING_BODY=$(git log $COMMIT_RANGE --grep="BREAKING CHANGE" --not --grep="^release" --oneline)
            
            echo "🔍 DEBUG: Breaking commits found:"
            echo "$BREAKING_COMMITS"
            echo "🔍 DEBUG: Breaking change body found:"
            echo "$BREAKING_BODY"
            
            if [[ -n "$BREAKING_COMMITS" ]] || [[ -n "$BREAKING_BODY" ]]; then
              echo "version-bump=major" >> $GITHUB_OUTPUT
              echo "has-breaking=true" >> $GITHUB_OUTPUT
              echo "🚀 Major release - breaking changes detected in commit history"
            else
              # Check for features (exclude previous release commits)
              FEATURE_COMMITS=$(git log $COMMIT_RANGE --grep="^feat:" --not --grep="^release" --oneline)
              if [[ -n "$FEATURE_COMMITS" ]]; then
                echo "version-bump=minor" >> $GITHUB_OUTPUT
                echo "🎉 Minor release - new features detected"
              else
                echo "version-bump=patch" >> $GITHUB_OUTPUT
                echo "🐛 Patch release - only fixes and other changes"
              fi
            fi
          fi
          echo "📦 Release commit detected - will create release PR"
        else
          echo "should-create-pr=false" >> $GITHUB_OUTPUT
          echo "ℹ️ Not a release commit (must start with 'release:' or 'release!:')"
        fi




