name: tag-upsert-batch
description: "Create or update many tags from JSON [{tag, sha, message?}]"

inputs:
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  sign:
    description: "Sign the tag? 'auto' (default) signs if a GPG key is provided; 'true' forces signing; 'false' disables it."
    required: false
    default: "auto"
  annotate:
    description: "Create an annotated tag? 'auto' (default) annotates if signing or a message is provided; 'true' forces annotated; 'false' creates a lightweight tag."
    required: false
    default: "auto"
  tagger_name:
    description: "Tagger name (defaults to bot/user name if unset)"
    required: false
  tagger_email:
    description: "Tagger email (defaults to bot/user email if unset)"
    required: false
  gpg_private_key:
    description: "ASCII-armored private key for signing (if provided and sign=auto/true)"
    required: false
  gpg_passphrase:
    description: "Passphrase for the private key (if applicable)"
    required: false
  push:
    description: "Push the tag to origin after creation/update (default true)"
    required: false
    default: "true"
  payload:
    description: 'JSON array: [{"tag":"vX.Y.Z","sha":"<commit>","message":"optional"}, ...]'
    required: true
  repo:
    description: "owner/repo (defaults to current repository)"
    required: false

outputs:
  report:
    description: 'Compact JSON array of results per tag (e.g., [{"tag":"v2.0.0","action":"create","tag_obj_sha":"..."}, ...])'

runs:
  using: node20
  main: action.mjs
