name: "Detect Repository Config"
description: "Composite action for detecting repository configuration"

inputs:
  package-manager:
    description: "Package manager (npm or yarn)"
    required: false
    default: "npm"
  custom-npm-command:
    description: "Custom NPM publish command"
    required: false
    default: ""
  custom-github-packages-command:
    description: "Custom GitHub Packages publish command"
    required: false
    default: ""
  github-token:
    description: "GitHub token for API operations"
    required: true

outputs:
  npm-command:
    description: "NPM publish command"
    value: ${{ steps.detect.outputs.npm-command }}
  github-packages-command:
    description: "GitHub Packages publish command"
    value: ${{ steps.detect.outputs.github-packages-command }}
  repo-is-private:
    description: "Whether repository is private"
    value: ${{ steps.detect.outputs.repo-is-private }}

runs:
  using: composite
  steps:
    - name: Detect repository configuration
      id: detect
      uses: CLDMV/.github/.github/actions/github/utilitie@v1
      with:
        package-manager: ${{ inputs.package-manager }}
        custom-npm-command: ${{ inputs.custom-npm-command }}
        custom-github-packages-command: ${{ inputs.custom-github-packages-command }}
        github-token: ${{ inputs.github-token }}



