name: "Build Project"
description: "Build project with configurable command and environment"

inputs:
  build-command:
    description: "Command to build the project"
    required: true
  environment:
    description: "Environment to build for (production, development)"
    required: false
    default: "production"
  
runs:
  using: "composite"
  steps:
    - name: Build project
      shell: bash
      run: ${{ inputs.build-command }}
      env:
        NODE_ENV: ${{ inputs.environment }}




