name: "🔧 Fix Orphaned Major/Minor Version Tags"
description: "Detects major/minor version tags that don't point to the latest patch and fixes them via tag/upsert-batch"

inputs:
  repo:
    description: "owner/repo (defaults to current repository)"
    required: false
  run_mode:
    description: "Mode: 'detect' to only detect, 'fix' to also repair tags via upsert-batch"
    required: false
    default: "fix"
  sign:
    description: "Smart signing mode for retagging (auto/true/false)"
    required: false
    default: "auto"
  annotate:
    description: "Smart annotate mode (auto/true/false)"
    required: false
    default: "auto"
  tagger_name:
    description: "Tagger name"
    required: false
  tagger_email:
    description: "Tagger email"
    required: false
  gpg_private_key:
    description: "ASCII-armored private key for signing"
    required: false
  gpg_passphrase:
    description: "Passphrase for the private key (if protected)"
    required: false

outputs:
  fixed-tags:
    description: "Multiline list of tags that were (or would be) retargeted in this run"
    value: ${{ steps.gather.outputs.fixed-tags }}
  orphans-found:
    description: "'true' if any orphaned tags were detected (and possibly fixed), otherwise 'false'"
    value: ${{ steps.gather.outputs.orphans-found }}
  orphaned-tags-json:
    description: "Compact JSON array of {tag, sha} to retarget (input for tag/upsert-batch)"
    value: ${{ steps.gather.outputs.orphaned-tags-json }}

runs:
  using: "composite"
  steps:
    - name: Checkout code (full history for tags)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect orphaned major/minor tags
      id: gather
      run: node $GITHUB_ACTION_PATH/action.mjs
      shell: bash
      env:
        REPO: ${{ inputs.repo || github.repository }}

    - name: Fix orphaned tags (via tag/upsert-batch)
      if: ${{ steps.gather.outputs.orphans-found == 'true' && inputs.run_mode == 'fix' }}
      uses: CLDMV/.github/.github/actions/github/api/tag/upsert-batch@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repo: ${{ inputs.repo || github.repository }}
        payload: ${{ steps.gather.outputs.orphaned-tags-json }}
        sign: ${{ inputs.sign }}
        annotate: ${{ inputs.annotate }}
        tagger_name: ${{ inputs.tagger_name }}
        tagger_email: ${{ inputs.tagger_email }}
        gpg_private_key: ${{ inputs.gpg_private_key }}
        gpg_passphrase: ${{ inputs.gpg_passphrase }}
