name: "Get Node.js Version"
description: "Outputs the normalized Node.js version (e.g., 20.11.1) and a label (e.g., lts) if input was lts/*"

inputs:
  label:
    description: "Optional label to use instead of version (e.g., lts)"
    required: false
    default: ""

outputs:
  node-version:
    description: "Normalized Node.js version (e.g., 20.11.1)"
  node-label:
    description: "Label for this version (e.g., lts, 18.x, etc.)"

runs:
  using: "node24"
  main: "action.mjs"
