name: Reusable Release Please
on:
  workflow_call:
    inputs:
      package_name:
        type: string
        required: true
      default_branch:
        type: string
        default: master
      node_version:
        type: string
        default: "lts/*"
    secrets: {}
jobs:
  release_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Opens/updates a Release PR with version bump + CHANGELOG
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          package-name: ${{ inputs.package_name }}
          default-branch: ${{ inputs.default_branch }}
          # Optional: customize changelog types or PR title pattern if you want
