name: "Add Success Comment"
description: "Add a success comment to the commit with package publication details"

inputs:
  version:
    description: "Published version"
    required: true
  package-name:
    description: "Name of the published package"
    required: true
  npm-published:
    description: "Whether package was published to NPM"
    required: false
    default: "false"
  github-packages-published:
    description: "Whether package was published to GitHub Packages"
    required: false
    default: "false"
  publish-to-npm:
    description: "Whether NPM publishing was enabled"
    required: false
    default: "false"
  publish-to-github-packages:
    description: "Whether GitHub Packages publishing was enabled"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Add success comment to commit
      uses: actions/github-script@v7
      with:
        script: |
          const version = '${{ inputs.version }}';
          const packageName = '${{ inputs.package-name }}';
          const publishToNPM = '${{ inputs.publish-to-npm }}' === 'true';
          const publishToGitHub = '${{ inputs.publish-to-github-packages }}' === 'true';
          const npmPublished = '${{ inputs.npm-published }}' === 'true';
          const githubPublished = '${{ inputs.github-packages-published }}' === 'true';

          let comment = `🎉 **Package published successfully!**

          🏷️ **Version:** ${version}`;

          if (publishToNPM && npmPublished) {
            comment += `

          📦 **NPM:** [${packageName}@${version}](https://www.npmjs.com/package/${packageName}/v/${version})
          📥 **Install:** \`npm install ${packageName}@${version}\``;
          }

          if (publishToGitHub && githubPublished) {
            comment += `

          📦 **GitHub Packages:** [${packageName}@${version}](https://github.com/${{ github.repository }}/packages/)
          📥 **Install from GitHub:** \`npm install --registry=https://npm.pkg.github.com ${packageName}@${version}\``;
          }

          comment += `

          The package is now available for installation! 🚀`;

          try {
            // Get the latest commit SHA from the default branch
            const { data: ref } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/' + context.ref.replace('refs/heads/', '')
            });
            
            const commitSha = ref.object.sha;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
              body: comment
            });
            
            console.log(`✅ Successfully added comment to commit ${commitSha}`);
          } catch (error) {
            console.log(`⚠️ Failed to add commit comment: ${error.message}`);
            // Don't fail the workflow if comment creation fails
          }
