# CLDMV/.github/.github/workflows/release.yml
name: Release Workflow (Org-Level)

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
        description: "NPM package name (e.g., @cldmv/slothlet)"
      node_version:
        required: false
        type: string
        default: "lts/*"
        description: "Node.js version to use (default: lts/*)"
      min_node_version:
        required: false
        type: string
        default: "20"
        description: "Minimum Node.js version for matrix testing (default: 20, oldest non-EOL)"
      max_node_major:
        required: false
        type: string
        default: "22"
        description: "Override max Node.js major version (default: 22)"
      package_manager:
        required: false
        type: string
        default: "npm"
        description: "Package manager (npm or yarn)"
      test_command:
        required: false
        type: string
        default: "npm test"
        description: "Command to run tests"
      build_command:
        required: false
        type: string
        default: "npm run build:ci"
        description: "Command to build package"
      version_bump:
        required: false
        type: string
        default: "patch"
        description: "Type of version bump (major, minor, patch)"
      # Optional release parameters
      version:
        required: false
        type: string
        default: ""
        description: "Specific version for release (auto-calculated if not provided)"
      is_prerelease:
        required: false
        type: boolean
        default: false
        description: "Whether this is a prerelease"
      release_source_only:
        required: false
        type: boolean
        default: false
        description: "Whether to create source-only release (no package assets)"
      create_documentation:
        required: false
        type: boolean
        default: true
        description: "Whether to create/update VERSION_TAGS.md"
      # Test control options
      skip_performance_tests:
        required: false
        type: boolean
        default: false
        description: "Skip performance tests during CI"
      skip_matrix_tests:
        required: false
        type: boolean
        default: false
        description: "Skip matrix testing (use single node version only)"
    outputs:
      release-pr-created:
        description: "Whether a release PR was created"
        value: ${{ jobs.release.outputs.pr-created }}
      release-pr-number:
        description: "The release PR number if created"
        value: ${{ jobs.release.outputs.pr-number }}
      new-version:
        description: "The new version that was set"
        value: ${{ jobs.release.outputs.new-version }}

    secrets:
      NPM_TOKEN:
        description: "NPM token for publishing packages"
        required: false

jobs:
  release:
    name: "🚀 Release Management"
    uses: ./.github/workflows/ci-jobs.yml
    with:
      package_name: ${{ inputs.package_name }}
      run_build_and_test: true
      run_detect_release: true
      run_create_release_pr: true
      node_version: ${{ inputs.node_version }}
      min_node_version: ${{ inputs.min_node_version }}
      max_node_major: ${{ inputs.max_node_major }}
      package_manager: ${{ inputs.package_manager }}
      test_command: ${{ inputs.test_command }}
      build_command: ${{ inputs.build_command }}
      version_bump: ${{ inputs.version_bump }}
      version: ${{ inputs.version }}
      is_prerelease: ${{ inputs.is_prerelease }}
      release_source_only: ${{ inputs.release_source_only }}
      create_documentation: ${{ inputs.create_documentation }}
      skip_performance_tests: ${{ inputs.skip_performance_tests }}
      skip_matrix_tests: ${{ inputs.skip_matrix_tests }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
