name: tag-create
description: "Create a VERIFIED annotated tag for a commit (or move existing tag ref to the new tag object)"

inputs:
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  gpg_enabled:
    description: "Whether GPG signing should be used (auto-detected from workflow)"
    required: false
    default: "false"
  tagger_name:
    description: "Tagger name (defaults to bot/user name if unset)"
    required: false
  tagger_email:
    description: "Tagger email (defaults to bot/user email if unset)"
    required: false
  gpg_private_key:
    description: "ASCII-armored private key for signing (if provided and sign=auto/true)"
    required: false
  gpg_passphrase:
    description: "Passphrase for the private key (if applicable)"
    required: false
  push:
    description: "Push the tag to origin after creation/update (default true)"
    required: false
    default: "true"
  tag:
    description: "Tag name to create (e.g., v2.0.0)"
    required: true
  sha:
    description: "Target commit SHA the tag should reference"
    required: true
  message:
    description: "Annotated tag message (defaults to tag name)"
    required: false
  repo:
    description: "owner/repo (defaults to current repository)"
    required: false

outputs:
  tag_obj_sha:
    description: "SHA of the created annotated tag object"
  ref_sha:
    description: "Final SHA of refs/tags/<tag> (points at the tag object)"

runs:
  using: node20
  main: action.mjs
